"""empty message

Revision ID: 09a2407ea8df
Revises: dc57e34e5565
Create Date: 2020-08-22 22:36:08.597198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a2407ea8df'
down_revision = 'dc57e34e5565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermessage', sa.Column('group_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermessage', 'group_id')
    # ### end Alembic commands ###
