"""empty message

Revision ID: 1d349a62e837
Revises: e6efe2d54041
Create Date: 2020-08-23 14:41:44.009336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d349a62e837'
down_revision = 'e6efe2d54041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermessage', sa.Column('account', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermessage', 'account')
    # ### end Alembic commands ###
