"""empty message

Revision ID: bdaccba253c6
Revises: 1d349a62e837
Create Date: 2020-08-23 15:07:49.973478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdaccba253c6'
down_revision = '1d349a62e837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermessage', sa.Column('status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermessage', 'status')
    # ### end Alembic commands ###
