"""empty message

Revision ID: e6efe2d54041
Revises: 09a2407ea8df
Create Date: 2020-08-23 11:41:00.156367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6efe2d54041'
down_revision = '09a2407ea8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermessage', sa.Column('type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermessage', 'type')
    # ### end Alembic commands ###
