"""empty message

Revision ID: 455e672122c0
Revises: 
Create Date: 2020-08-13 21:06:36.553659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455e672122c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Entry',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Entry')
    # ### end Alembic commands ###
